e-commerce/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using e_commerce.ViewModel;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class CartsController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
        private readonly string CustomerURL = ApiURLS.GetCustomerUrl();
        private readonly string ElectronicURL = ApiURLS.GetElectronicDevicesUrl();
        private readonly string FashionURL =ApiURLS.GetFashionUrl();
        private readonly string HomeDecorURL =ApiURLS.GetHomeDecorUrl();
        private readonly string OrderReviewURL = ApiURLS.GetOrderReviewUrl();
        private readonly string CartURL = ApiURLS.GetCartUrl();

        public CartsController(ShoppingDbContext context)
        {
            _context = context;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
           if(HttpContext.Session.GetString("username1")!=null)
            {
                var shoppingDbContext = JsonConvert.DeserializeObject<List<Cart>>(await client.GetStringAsync(CartURL)).ToList().Where(a => a.Userid.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));

               // var shoppingDbContext = _context.Cart.Include(c => c.Customer).Where(a=>a.Userid.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));
                var count = shoppingDbContext.ToList().Count();
                HttpContext.Session.SetString("CartCount", count.ToString());
                if (shoppingDbContext!= null && count>0)
                {
                    return View(shoppingDbContext.ToList());
                }
                else
                {
                    return RedirectToAction("CartEmpty");
                }
               
            }
            else
            {
                return RedirectToAction("Customer", "Login");
            }

        }

        public ActionResult CartEmpty()
        {
            return View();
        }
        public async Task<IActionResult> GetElectronic(int id)
        {
            var ElectronList = JsonConvert.DeserializeObject<List<ElectronicDevice>>(await client.GetStringAsync(ElectronicURL)).ToList();
            var productobj = ElectronList.FirstOrDefault(a => a.EId.Equals(id));
            HttpContext.Session.SetString("EId", productobj.EId.ToString());
            HttpContext.Session.SetString("Ename", productobj.EName.ToString());
            HttpContext.Session.SetString("ECategory", productobj.Category.ToString());
            HttpContext.Session.SetString("EPrice", productobj.Price.ToString());
            HttpContext.Session.SetString("EQuantity", productobj.Quantity.ToString());
            HttpContext.Session.SetString("ERating", productobj.Rating.ToString());
            HttpContext.Session.SetString("ELaunchDate", productobj.LaunchDate.ToString());
            HttpContext.Session.SetString("EImageFile", productobj.ImageFile.ToString());
            HttpContext.Session.SetString("EBrand", productobj.EBrand.ToString());
            HttpContext.Session.SetString("EDescription", productobj.Description.ToString());
            HttpContext.Session.SetString("EFreeDelivery", productobj.FreeDelivery.ToString());
            HttpContext.Session.SetString("EActive", productobj.Active.ToString());
            
            return RedirectToAction("EGetQuantity");

        }

        public ActionResult EGetQuantity()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EGetQuantity(ElectronicViewModel electronicViewModel)
        {
           
            Cart c = new Cart();
            c.Userid = Convert.ToInt32(HttpContext.Session.GetString("custId"));
            c.productName = HttpContext.Session.GetString("Ename");
            c.Price = Convert.ToInt32(HttpContext.Session.GetString("EPrice"));
            c.Quantity = electronicViewModel.Quantity;
            c.productImage = HttpContext.Session.GetString("EImageFile");
            c.Description = HttpContext.Session.GetString("EDescription");
            c.FreeDelivery = Convert.ToBoolean(HttpContext.Session.GetString("EFreeDelivery"));
            c.Category = HttpContext.Session.GetString("ECategory");
            c.Brand = HttpContext.Session.GetString("EBrand");

            // _context.Cart.Add(c);
            // _context.SaveChanges();
            await client.PostAsJsonAsync<Cart>(CartURL, c);
            TempData["ECart"] = "Item Added To Cart Successfully";
            return RedirectToAction("Index");
        }

        //Get Fashion Product
        public async Task<IActionResult> GetFashion(int id)
        {
            var FashionList = JsonConvert.DeserializeObject<List<Fashion>>(await client.GetStringAsync(FashionURL)).ToList();
            var productobj1 = FashionList.FirstOrDefault(a => a.FId.Equals(id));
            HttpContext.Session.SetString("FId", productobj1.FId.ToString());
            HttpContext.Session.SetString("Fname", productobj1.FName.ToString());
            HttpContext.Session.SetString("Ftype", productobj1.FType.ToString());
            HttpContext.Session.SetString("FSubCategory", productobj1.SubCategory.ToString());
            HttpContext.Session.SetString("FPrice", productobj1.Price.ToString());
            HttpContext.Session.SetString("FQuantity", productobj1.Quantity.ToString());
            HttpContext.Session.SetString("FLaunchDate", productobj1.LaunchDate.ToString());
            HttpContext.Session.SetString("FFreeDelivery", productobj1.FreeDelivery.ToString());
            HttpContext.Session.SetString("FRating", productobj1.Rating.ToString());
            HttpContext.Session.SetString("FImageFile", productobj1.ImageFile.ToString());
            HttpContext.Session.SetString("FActive", productobj1.Active.ToString());
            HttpContext.Session.SetString("FBrand", productobj1.FBrand.ToString());
            HttpContext.Session.SetString("FDescription", productobj1.Description.ToString());
            
           

            return RedirectToAction("FGetQuantity");

        }

        public ActionResult FGetQuantity()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> FGetQuantity(FashionViewModel fashionViewModel)
        {

            Cart c = new Cart();
            c.Userid = Convert.ToInt32(HttpContext.Session.GetString("custId"));
            c.productName = HttpContext.Session.GetString("Fname");
            c.Price = Convert.ToInt32(HttpContext.Session.GetString("FPrice"));
            c.Quantity = fashionViewModel.Quantity;
            c.productImage = HttpContext.Session.GetString("FImageFile");
            c.Description = HttpContext.Session.GetString("FDescription");
            c.FreeDelivery = Convert.ToBoolean(HttpContext.Session.GetString("FFreeDelivery"));
            c.Category = HttpContext.Session.GetString("FSubCategory");
            c.Brand = HttpContext.Session.GetString("FBrand");

            //_context.Cart.Add(c);
            // _context.SaveChanges();
            await client.PostAsJsonAsync<Cart>(CartURL, c);
            TempData["FCart"] = "Item Added To Cart Successfully";
            return RedirectToAction("Index");
        }



        //Get Home Decor Product
        public async Task<IActionResult> GetHomeDecor(int id)
        {
            var HomeDecorsList = JsonConvert.DeserializeObject<List<HomeDecor>>(await client.GetStringAsync(HomeDecorURL)).ToList();
            var productobj = HomeDecorsList.FirstOrDefault(a => a.HId.Equals(id));
            HttpContext.Session.SetString("HId", productobj.HId.ToString());
            HttpContext.Session.SetString("Hname", productobj.HName.ToString());
            HttpContext.Session.SetString("Htype", productobj.HType.ToString());          
            HttpContext.Session.SetString("HPrice", productobj.Price.ToString());
            HttpContext.Session.SetString("HQuantity", productobj.Quantity.ToString());
            HttpContext.Session.SetString("HRating", productobj.Rating.ToString());
            HttpContext.Session.SetString("HLaunchDate", productobj.LaunchDate.ToString());
            HttpContext.Session.SetString("HImageFile", productobj.ImageFile.ToString());
            HttpContext.Session.SetString("HBrand", productobj.HBrand.ToString());
            HttpContext.Session.SetString("HDescription", productobj.Description.ToString());
            HttpContext.Session.SetString("HFreeDelivery", productobj.FreeDelivery.ToString());
            HttpContext.Session.SetString("HActive", productobj.Active.ToString());

            return RedirectToAction("HGetQuantity");

        }

        public ActionResult HGetQuantity()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> HGetQuantity(HomeDecorViewModel homeDecorViewModel)
        {

            Cart c = new Cart();
            c.Userid = Convert.ToInt32(HttpContext.Session.GetString("custId"));
            c.productName = HttpContext.Session.GetString("Hname");
            c.Price = Convert.ToInt32(HttpContext.Session.GetString("HPrice"));
            c.Quantity = homeDecorViewModel.Quantity;
            c.productImage = HttpContext.Session.GetString("HImageFile");
            c.Description = HttpContext.Session.GetString("HDescription");
            c.FreeDelivery = Convert.ToBoolean(HttpContext.Session.GetString("HFreeDelivery"));
            c.Category = HttpContext.Session.GetString("Htype");
            c.Brand = HttpContext.Session.GetString("HBrand");

            //_context.Cart.Add(c);

e-commerce/Controllers/CustomerFashionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class CustomerFashionsController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
        private readonly string FashionURL = ApiURLS.GetFashionUrl();

        public CustomerFashionsController(ShoppingDbContext context)
        {
            _context = context;
        }

        // GET: CustomerFashions
        public async Task<IActionResult> Index()
        {
            // return View(await _context.Fashion.ToListAsync());
            return View(JsonConvert.DeserializeObject<List<Fashion>>(await client.GetStringAsync(FashionURL)).ToList());
        }

        public async Task<IActionResult> FList()
        {
            return View(JsonConvert.DeserializeObject<List<Fashion>>(await client.GetStringAsync(FashionURL)).ToList());
        }

        public async Task<IActionResult> Watch()
        {
            var WatchList = JsonConvert.DeserializeObject<List<Fashion>>(await client.GetStringAsync(FashionURL)).ToList();
            return View(WatchList.Where(a => a.SubCategory.Equals(Scategory.Watch)));
        }

        // GET: CustomerFashions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var fashion = await _context.Fashion
            //  .FirstOrDefaultAsync(m => m.FId == id);
            var fashion = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(FashionURL + id));
            if (fashion == null)
            {
                return NotFound();
            }

            return View(fashion);
        }

        // GET: CustomerFashions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CustomerFashions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FId,FName,FType,SubCategory,Price,Quantity,LaunchDate,FreeDelivery,Rating,ImageFile,Active,FBrand,Description")] Fashion fashion)
        {
            if (ModelState.IsValid)
            {
                // _context.Add(fashion);
                //await _context.SaveChangesAsync();
                await client.PostAsJsonAsync<Fashion>(FashionURL, fashion);
                return RedirectToAction(nameof(Index));
            }
            return View(fashion);
        }

        // GET: CustomerFashions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var fashion = await _context.Fashion.FindAsync(id);
            var fashion = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(FashionURL + id));
            if (fashion == null)
            {
                return NotFound();
            }
            return View(fashion);
        }

        // POST: CustomerFashions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FId,FName,FType,SubCategory,Price,Quantity,LaunchDate,FreeDelivery,Rating,ImageFile,Active,FBrand,Description")] Fashion fashion)
        {
            if (id != fashion.FId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // _context.Update(fashion);
                    // await _context.SaveChangesAsync();
                    await client.PutAsJsonAsync<Fashion>(FashionURL + id, fashion);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var fashions = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(FashionURL + id));
                    if (!(fashions.FId== fashion.FId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fashion);
        }

        // GET: CustomerFashions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var fashion = await _context.Fashion
            // .FirstOrDefaultAsync(m => m.FId == id);
            var fashion = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(FashionURL + id));
            if (fashion == null)
            {
                return NotFound();
            }

            return View(fashion);
        }

        // POST: CustomerFashions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //var fashion = await _context.Fashion.FindAsync(id);
            // _context.Fashion.Remove(fashion);
            //await _context.SaveChangesAsync();
            await client.DeleteAsync(FashionURL + id);
            return RedirectToAction(nameof(Index));
        }

        private bool FashionExists(int id)
        {
            return _context.Fashion.Any(e => e.FId == id);
        }
    }
}

e-commerce/Views/CustomerFashions/Details.cshtml
@model e_commerce.Models.Fashion

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}
<head>
    <style>
        dt {
            float: left;
            clear: left;
            width: 110px;
            font-weight: bold;
        }

            dt::after {
                content: ":";
            }

        dd {
            margin: 0 0 0 80px;
            padding: 0 0 0.5em 0;
        }
    </style>
</head>
<h2>Details</h2>

<div>
    <h4>Fashion</h4>
    <hr />
    <div class="row">
        <div class="col-sm-3">
            <img src="@Html.DisplayFor(model => model.ImageFile)" class="card-img-top overflow-auto" alt="..." />
        </div>
        <div class="col-sm-9">
            <dl>
               <dt>
                    @Html.DisplayNameFor(model => model.FName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.FName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.FType)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.FType)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.SubCategory)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.SubCategory)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Quantity)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Quantity)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.LaunchDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.LaunchDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.FreeDelivery)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.FreeDelivery)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Rating)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Rating)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Active)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Active)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.FBrand)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.FBrand)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
            <div>
                <a asp-controller="Carts" asp-action="GetFashion" asp-route-id="@Model.FId" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span>Add to Cart</a> |
                <a class="btn btn-primary" asp-action="CustomerView" asp-controller="Login">Back to List</a>
            </div>


        </div>
        
    </div>
    
</div>

e-commerce/Views/CustomerFashions/FList.cshtml
@model IEnumerable<e_commerce.Models.Fashion>

@{
    ViewData["Title"] = "FList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Fashion</title>



    <!-- Bootstrap -->

    <link href="Bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js></script>

    <script src=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">





    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

      <script src=https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js></script>

      <script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script>

    <![endif]-->

    <style>

        .i-plain:hover {
            color: red
        }
    </style>

</head>

<body>



    <div class="container-fluid padding">

        <h2>Fashion Products</h2>
        <a class="btn btn-lg btn-primary" asp-action="Index" style="justify-content:right" asp-controller="Home">Back to Home</a>

        <br />

        <div class="row overflow-auto">
            @foreach (var item in Model)
            {

                <div class="col-md-3 overflow-auto">



                    <div class="card h-100" style="background-image: url('https://media.istockphoto.com/vectors/crepe-paper-textured-grunge-vector-tricolour-faded-background-with-vector-id1264073605?k=6&m=1264073605&s=612x612&w=0&h=P31yF3S7XWPIvIINd5uTfuwl1MUa0nqzTRRaG0mFay4='); backdrop-filter: blur(50px); background-size:cover; background-repeat: no-repeat;">


                        <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." />

                        <div class="card-body">

                            <h5 class="card-title">

                                <b>@item.FName</b>

                                <span class="bg-success" style="color:white">

                                    @item.Rating

                                    <span class="glyphicon glyphicon-star"></span>

                                </span>

                            </h5>

                            <h5 class="card-title">Rs @item.Price <span>  20%  </span><span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>

                            <br>

                            <p class="card-text">@item.Description</p>
                            <div class="view overlay">

                                <a asp-controller="Login" asp-action="Customer" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span>Add to Cart</a>

                                <a href="#" style="text-align:right" class=""><span class="glyphicon glyphicon-heart-empty i-plain"></span></a>

                            </div>


                        </div>





                    </div>
                    <br />

                </div>

            }
        </div>

    </div>





    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js></script>



    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="Bootstrap/js/bootstrap.min.js"></script>

</body>

</html>

e-commerce/Views/CustomerFashions/Index.cshtml
@model IEnumerable<e_commerce.Models.Fashion>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Fashion</title>



    <!-- Bootstrap -->

    <link href="Bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js></script>

    <script src=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">





    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

      <script src=https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js></script>

      <script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script>

    <![endif]-->

    <style>

        .i-plain:hover {
            color: red
        }
    </style>

</head>

<body>



    <div class="container-fluid padding">

        <h2>Fashion Products</h2>

        <br />

        <div class="row overflow-auto">
            @foreach (var item in Model)
            {

                <div class="col-md-3 overflow-auto">



                    <div class="card h-100" style="background-image: url('https://media.istockphoto.com/vectors/crepe-paper-textured-grunge-vector-tricolour-faded-background-with-vector-id1264073605?k=6&m=1264073605&s=612x612&w=0&h=P31yF3S7XWPIvIINd5uTfuwl1MUa0nqzTRRaG0mFay4='); backdrop-filter: blur(50px); background-size:cover; background-repeat: no-repeat;">


                        <a asp-controller="CustomerFashions" asp-action="Details" asp-route-id="@item.FId"> <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." /></a>

                        <div class="card-body">

                            <h5 class="card-title">

                                <b>@item.FName</b>

                                <span class="bg-success" style="color:white">

                                    @item.Rating

                                    <span class="glyphicon glyphicon-star"></span>

                                </span>

                            </h5>

                            <h5 class="card-title">Rs @item.Price <s>Rs. 250 </s> 20% <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>

                            <br>

                            <p class="card-text">@item.Description</p>
                            <div class="view overlay">

                                <a asp-controller="Carts" asp-action="GetFashion" asp-route-id="@item.FId" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span>Add to Cart</a>

                                <a href="#" style="text-align:right" class=""><span class="glyphicon glyphicon-heart-empty i-plain"></span></a>

                            </div>


                        </div>





                    </div>
                    <br />

                </div>

            }
        </div>

    </div>





    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js></script>



    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="Bootstrap/js/bootstrap.min.js"></script>

</body>

</html>