e-commerce/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace e_commerce.Models
{
    public class Customer
    {
        [Key]
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please Enter the FirstName")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter the LastName")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please Enter the Email ")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter the UserName")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please Enter the Password")]
        [MaxLength(12)]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Compare("Password", ErrorMessage = "Please confirm your password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Please enter money")]
        public int Balance { get; set; }
        
    }
}

e-commerce/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using e_commerce.ViewModel;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
        string CustomerURL = ApiURLS.GetCustomerUrl();

        public CustomersController(ShoppingDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {

            return View(JsonConvert.DeserializeObject<List<Customer>>(await client.GetStringAsync(CustomerURL)).ToList());
        }

        public IActionResult ForgotPassword()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ForgotPassword(ForgetPasswordViewModel forgetPasswordViewModel)
        {
            var customerList = JsonConvert.DeserializeObject<List<Customer>>(await client.GetStringAsync(CustomerURL)).ToList();
            var customerobj = customerList.FirstOrDefault(a => a.Email.Equals(forgetPasswordViewModel.EmailId));
            //var customerobj = _context.Customer.FirstOrDefault(a => a.Email.Equals(forgetPasswordViewModel.EmailId));
            if (customerobj != null)
            {
                if(forgetPasswordViewModel.NewPassword == forgetPasswordViewModel.ConfirmPassword)
                {
                    customerobj.Password = forgetPasswordViewModel.NewPassword;
                    customerobj.ConfirmPassword = forgetPasswordViewModel.ConfirmPassword;
                    
                    await client.PutAsJsonAsync<Customer>(CustomerURL + customerobj.UserId, customerobj);
                    //_context.Customer.Update(customerobj);
                    //_context.SaveChanges();
                    return RedirectToAction("Customer", "Login");
                }
                else
                {
                    ModelState.AddModelError("Error", "Please check Confirm Password");
                }
               

            }
            else
            {
                ModelState.AddModelError("Error", "Please Enter Registered Email Address");
            }
            return View(forgetPasswordViewModel);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var customer = await _context.Customer
            // .FirstOrDefaultAsync(m => m.UserId == id);
            var customer = JsonConvert.DeserializeObject<Customer>(await client.GetStringAsync(CustomerURL + id));
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,FirstName,LastName,Email,UserName,Password,ConfirmPassword,Balance")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                //_context.Add(customer);
                //await _context.SaveChangesAsync();
                await client.PostAsJsonAsync<Customer>(CustomerURL, customer);
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var customer = await _context.Customer.FindAsync(id);
            var customer = JsonConvert.DeserializeObject<Customer>(await client.GetStringAsync(CustomerURL + id));
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,FirstName,LastName,Email,UserName,Password,ConfirmPassword,Balance")] Customer customer)
        {
            if (id != customer.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // _context.Update(customer);
                    //await _context.SaveChangesAsync();
                    await client.PutAsJsonAsync<Customer>(CustomerURL + id, customer);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var customers = JsonConvert.DeserializeObject<Customer>(await client.GetStringAsync(CustomerURL + id));
                    if (!(customers.UserId== customer.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("CMyAccount","Login");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var customer = await _context.Customer
            // .FirstOrDefaultAsync(m => m.UserId == id);
            var customer = JsonConvert.DeserializeObject<Customer>(await client.GetStringAsync(CustomerURL + id));

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // var customer = await _context.Customer.FindAsync(id);
            //_context.Customer.Remove(customer);
            //await _context.SaveChangesAsync();
            await client.DeleteAsync(CustomerURL + id);
            return RedirectToAction("CMyAccount","Login");
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.UserId == id);
        }
    }
}

e-commerce/Controllers/FashionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class FashionsController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
        string url = ApiURLS.GetFashionUrl();

        public FashionsController(ShoppingDbContext context)
        {
            _context = context;
        }

        // GET: Fashions
        public async Task<IActionResult> Index()
        {
            // return View(await _context.Fashion.ToListAsync());
            return View(JsonConvert.DeserializeObject<List<Fashion>>(await client.GetStringAsync(url)).ToList());
        }

        // GET: Fashions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var fashion = await _context.Fashion
            // .FirstOrDefaultAsync(m => m.FId == id);
            var fashion = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(url + id));
            if (fashion == null)
            {
                return NotFound();
            }

            return View(fashion);
        }

        // GET: Fashions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fashions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FId,FName,FType,SubCategory,Price,Quantity,LaunchDate,FreeDelivery,Rating,ImageFile,Active,FBrand,Description")] Fashion fashion)
        {
            if (ModelState.IsValid)
            {
                TempData["FCreate"] = "Successfully Created";
                // _context.Add(fashion);
                // await _context.SaveChangesAsync();
                await client.PostAsJsonAsync<Fashion>(url, fashion);
                return RedirectToAction("AdminView", "Login");
            }
            else
            {
                ViewBag.FCreate = "Create Failed.";
                return View(fashion);
            }
        }

            // GET: Fashions/Edit/5
            public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var fashion = await _context.Fashion.FindAsync(id);
            var fashion = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(url + id));

            if (fashion == null)
            {
                return NotFound();
            }
            return View(fashion);
        }

        // POST: Fashions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FId,FName,FType,SubCategory,Price,Quantity,LaunchDate,FreeDelivery,Rating,ImageFile,Active,FBrand,Description")] Fashion fashion)
        {
            if (id != fashion.FId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Update(fashion);
                    //await _context.SaveChangesAsync();
                    await client.PutAsJsonAsync<Fashion>(url + id, fashion);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var fashions = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(url + id));
                    if (!(fashions.FId== fashion.FId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["FEdit"] = "Edited Successfully.";
                return RedirectToAction("AdminView","Login");
            }
            ViewBag.FEdit = "Edit Failed.";
            return View(fashion);
        }

        // GET: Fashions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var fashion = await _context.Fashion
            // .FirstOrDefaultAsync(m => m.FId == id);
            var fashion = JsonConvert.DeserializeObject<Fashion>(await client.GetStringAsync(url + id));
            if (fashion == null)
            {
                ViewBag.FDelete = "Product Not Found";
                return NotFound();
            }

            return View(fashion);
        }

        // POST: Fashions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //var fashion = await _context.Fashion.FindAsync(id);
            //_context.Fashion.Remove(fashion);
            // await _context.SaveChangesAsync();
            await client.DeleteAsync(url + id);
            TempData["FDelete"] = "Deleted Successfully";
            return RedirectToAction("AdminView", "Login");
        }

        private bool FashionExists(int id)
        {
            return _context.Fashion.Any(e => e.FId == id);
        }
    }
}

e-commerce/Views/Login/AMyAccount.cshtml
@model IEnumerable<e_commerce.Models.Admin>
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "AMyAccount";
    Layout = "~/Views/Shared/AdminViewPartial.cshtml";
}
<div class="container" style="background-color:lavender">
    <a class="btn btn-primary" asp-action="AdminView" asp-controller="Login">Back To Home</a>
    <br />

    <h2>My Account</h2>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.AdminAccountList)
            {

                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.UserName
                    </td>


                </tr>

            }
        </tbody>
    </table>
</div>

e-commerce/Views/Login/AdminView.cshtml
@model e_commerce.Context.ShoppingDbContext

@{
    ViewData["Title"] = "AdminView";
    Layout = "~/Views/Shared/AdminViewPartial.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Admin View</title>
    <!-- Bootstrap -->
    <link href="Bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src=https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js></script>
    <script src=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src=https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js></script>
      <script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script>
    <![endif]-->
    <style>
        .i-plain:hover {
            color: red
        }

        * {
            box-sizing: border-box
        }

        body {
            font-family: "Lato", sans-serif;
        }
        /* Style the tab */
        .tab {
            float: left;
            border: 1px solid #ccc;
            background-color: #f1f1f1;
            height: 1000px;
        }
            /* Style the buttons inside the tab */
            .tab button {
                display: block;
                background-color: inherit;
                color: black;
                padding: 22px 16px;
                width: 100%;
                border: none;
                outline: none;
                text-align: left;
                cursor: pointer;
                font-size: 17px;
            }
                /* Change background color of buttons on hover */
                .tab button:hover {
                    background-color: #ddd;
                }
                /* Create an active/current "tab button" class */
                .tab button.active {
                    background-color: #ccc;
                }
        /* Style the tab content */
        .tabcontent {
            float: left;
            padding: 0px 12px;
            width: 100%;
            height: 1000px;
            display: none;
        }
        /* Clear floats after the tab */
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
    </style>

    @if (TempData["AMessage"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["AMessage"]");
            };
        </script>
    }
    @if (TempData["ECreate"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["ECreate"]");
            };
        </script>
    }
    @if (TempData["EEdit"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["EEdit"]");
            };
        </script>
    }
    @if (TempData["EDelete"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["EDelete"]");
            };
        </script>
    }
    @if (TempData["FCreate"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["FCreate"]");
            };
        </script>
    }
    @if (TempData["FEdit"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["FEdit"]");
            };
        </script>
    }
    @if (TempData["FDelete"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["FDelete"]");
            };
        </script>
    }
    @if (TempData["HCreate"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["HCreate"]");
            };
        </script>
    }
    @if (TempData["HEdit"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["HEdit"]");
            };
        </script>
    }
    @if (TempData["HDelete"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["HDelete"]");
            };
        </script>
    }
</head>

<body style="background-color:lavender">


    <div class="col-sm-2">
        <div class="tab" style="background-color: #2d2d30">
            <button class="tablinks text-white" onmouseover="openCity(event, 'London')">Electronics</button><br />
            <button class="tablinks text-white" onmouseover="openCity(event, 'Paris')">Home Decors</button><br />
            <button class="tablinks text-white" onmouseover="openCity(event, 'Tokyo')">Fashion</button><br />
        </div>
    </div>
    
    <div class="col-sm-10">
        <div class="container-fluid padding">
            <div id="London" class="tabcontent">
                <h2>Electronics Product </h2>
                <br />
                <p>
                    <a class="btn btn-primary" role="button" asp-controller="ElectronicDevices" asp-action="Create">Create New Electronic</a>
                </p>
                <div class="row overflow-auto">
                    @foreach (var item in ViewBag.EleList)
                    {
                        <div class="col-md-3 overflow-auto">
                            <div class="card h-100" style="background-image: url('https://media.istockphoto.com/vectors/crepe-paper-textured-grunge-vector-tricolour-faded-background-with-vector-id1264073605?k=6&m=1264073605&s=612x612&w=0&h=P31yF3S7XWPIvIINd5uTfuwl1MUa0nqzTRRaG0mFay4='); backdrop-filter: blur(50px); background-size:cover; background-repeat: no-repeat;">
                                <a asp-controller="ElectronicDevices" asp-action="Details" asp-route-id="@item.EId"> <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." /></a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <b>@item.EName</b>
                                        <span class="bg-success" style="color:white">
                                            @item.Rating
                                            <span class="glyphicon glyphicon-star"></span>
                                        </span>
                                    </h5>
                                    <h5 class="card-title">Rs @item.Price <span> 20% </span><span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>
                                    <br>
                                    <p class="card-text">@item.Description</p>
                                </div>
                            </div>
                            <br />
                        </div>
                    }
                </div>
            </div>

            <div id="Paris" class="tabcontent">
                <h2>Home Decors Product </h2>
                <p>
                    <a class="btn btn-primary" role="button" asp-controller="HomeDecors" asp-action="Create">Create New Home Decors</a>
                </p>
                <div class="row overflow-auto">
                    @foreach (var item in ViewBag.HomeList)
                    {
                        <div class="col-md-3 overflow-auto">
                            <div class="card h-100"  style="background-image: url('https://media.istockphoto.com/vectors/crepe-paper-textured-grunge-vector-tricolour-faded-background-with-vector-id1264073605?k=6&m=1264073605&s=612x612&w=0&h=P31yF3S7XWPIvIINd5uTfuwl1MUa0nqzTRRaG0mFay4='); backdrop-filter: blur(50px); background-size:cover; background-repeat: no-repeat;">
                                <a asp-controller="HomeDecors" asp-action="Details" asp-route-id="@item.HId"> <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." /></a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <b>@item.HName</b>
                                        <span class="bg-success" style="color:white">
                                            @item.Rating
                                            <span class="glyphicon glyphicon-star"></span>
                                        </span>
                                    </h5>
                                    <h5 class="card-title">Rs @item.Price<span> 20% </span><span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>
                                    <br>
                                    <p class="card-text">@item.Description</p>
                                </div>
                            </div>
                            <br />
                        </div>
                    }
                </div>
            </div>

            <div id="Tokyo" class="tabcontent">
                <h2>Fashion Product</h2>
                <p>
                    <a class="btn btn-primary" role="button" asp-controller="Fashions" asp-action="Create">Create New Fashion</a>
                </p>
                <div class="row overflow-auto">
                    @foreach (var item in ViewBag.FashionList)
                    {
                        <div class="col-md-3 overflow-auto">
                            <div class="card h-100"  style="background-image: url('https://media.istockphoto.com/vectors/crepe-paper-textured-grunge-vector-tricolour-faded-background-with-vector-id1264073605?k=6&m=1264073605&s=612x612&w=0&h=P31yF3S7XWPIvIINd5uTfuwl1MUa0nqzTRRaG0mFay4='); backdrop-filter: blur(50px); background-size:cover; background-repeat: no-repeat;">
                                <a asp-controller="Fashions" asp-action="Details" asp-route-id="@item.FId"> <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." /></a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <b>@item.FName</b>
                                        <span class="bg-success" style="color:white">
                                            @item.Rating
                                            <span class="glyphicon glyphicon-star"></span>
                                        </span>
                                    </h5>
                                    <h5 class="card-title">Rs @item.Price<span> 20% </span><span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>
                                    <br>
                                    <p class="card-text">@item.Description</p>
                                </div>
                            </div>
                            <br />
                        </div>
                    }
                </div>
            </div>
            <div id="reviews" style="overflow:auto">
                <h2>Reviews</h2>
                <table class="table table-dark table-striped">
                   <thead>
                       <tr>
                           <th>User name</th>
                           <th>Rating</th>
                           <th>Status</th>
                           <th>Description</th>
                       </tr>
                   </thead>
                    <tbody>
                        @foreach(var item in ViewBag.ReviewList)
                        { 
                            <tr>
                                <td>@item.UserID</td>
                                <td>@item.O_Rating</td>
                                <td>@item.Status</td>
                                <td>@item.Description</td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>








    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js></script>



    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="Bootstrap/js/bootstrap.min.js"></script>
    <script>
        function openCity(evt, cityName) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(cityName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script>
    <script src="Bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

e-commerce/Views/Login/CMyAccount.cshtml
@model IEnumerable<e_commerce.Models.Customer>

@{
    ViewData["Title"] = "CMyAccount";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}
<div class="container-fluid" style="background-color:lavender">
<h2>My Account</h2>
<br />
<a class="btn btn-primary" asp-action="CustomerView" asp-controller="Login">Back To Home</a>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in ViewBag.Account1) {
        <tr>
            <td>
                @item.FirstName
            </td>
            <td>
                @item.LastName
            </td>
            <td>
                @item.Email
            </td>
            <td>
                @item.UserName
            </td>
            
            <td>
                <a class="btn btn-info" asp-action="Edit" asp-controller="Customers" asp-route-id="@item.UserId">Edit</a> |
                <a class="btn btn-primary" asp-action ="Details" asp-controller="Customers" asp-route-id="@item.UserId">Details</a> 
               
            </td>
        </tr>
}
    </tbody>
</table>
    </div>