e-commerce/Models/ElectronicDevice.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace e_commerce.Models
{
    public class ElectronicDevice
    {
        [Key]
        public int EId { get; set; }
        [Required(ErrorMessage ="Please Enter Product Name")]
        [Display(Name ="Product Name")]
        public string EName { get; set; }
        public Category Category { get; set; }
        [Required(ErrorMessage = "Please Enter Price")]
        public float Price { get; set; }
        [Required(ErrorMessage = "Please Enter  Quantity")]
        public int Quantity { get; set; }
        public int Rating { get; set; }
        [Required(ErrorMessage = "Please Enter Launch Date")]
        [Display(Name ="Launch Date")]
        public DateTime LaunchDate { get; set; }
        [Display(Name = "Image")]
        public string ImageFile { get; set; }
        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile ImageFile1 { get; set; }

        [Required(ErrorMessage = "Please Enter Brand")]
        [Display(Name = "Brand")]
        public EBrand EBrand { get; set; }
        public string Description { get; set; }
        [Display(Name = "Free Delivery")]
        public Boolean  FreeDelivery { get; set; }
        public Boolean Active { get; set; }
    }

    public enum Category
    {
        Laptop, Mobile, EarPhone, Camera, Television, Printers
    }

    public enum EBrand
    { 
        Bajaj, Sony, Lenovo, HP, RedMI, APPLE, OnePlus, Panasonic, Toshiba,Dell, Samsung, Intel, Microsoft, IBM
    }
}

e-commerce/Controllers/ElectronicDevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class ElectronicDevicesController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
        string url =ApiURLS.GetElectronicDevicesUrl();
        

        public ElectronicDevicesController(ShoppingDbContext context)
        {
            _context = context;
           
        }

        // GET: ElectronicDevices
        public async Task<IActionResult> Index()
        {

            // return View(await _context.ElectronicDevice.ToListAsync());
            return View(JsonConvert.DeserializeObject<List<ElectronicDevice>>(await client.GetStringAsync(url)).ToList());
        }
        
        // GET: ElectronicDevices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var electronicDevice = await _context.ElectronicDevice
            //   .FirstOrDefaultAsync(m => m.EId == id);
            var electronicDevice = JsonConvert.DeserializeObject<ElectronicDevice>(await client.GetStringAsync(url + id));
            if (electronicDevice == null)
            {
                return NotFound();
            }

            return View(electronicDevice);
        }

        // GET: ElectronicDevices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ElectronicDevices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EId,EName,Category,Price,Quantity,Rating,LaunchDate,ImageFile, EBrand,Description,FreeDelivery,Active")] ElectronicDevice electronicDevice)
        {

            if (ModelState.IsValid)
            {
                TempData["ECreate"] = "Successfully Created";
                // _context.Add(electronicDevice);
                // await _context.SaveChangesAsync();
                await client.PostAsJsonAsync<ElectronicDevice>(url, electronicDevice);
                return RedirectToAction("AdminView", "Login");
            }
            else
            {
                ViewBag.ECreate = "Create Failed.";
                return View(electronicDevice);
            }

           
        }

        // GET: ElectronicDevices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var electronicDevice = await _context.ElectronicDevice.FindAsync(id);
            var electronicDevice = JsonConvert.DeserializeObject<ElectronicDevice>(await client.GetStringAsync(url + id));

            if (electronicDevice == null)
            {
                return NotFound();
            }
            return View(electronicDevice);
        }

        // POST: ElectronicDevices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EId,EName,Category,Price,Quantity,Rating,LaunchDate,ImageFile,EBrand,Description,FreeDelivery,Active")] ElectronicDevice electronicDevice)
        {
            if (id != electronicDevice.EId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Update(electronicDevice);
                    await client.PutAsJsonAsync<ElectronicDevice>(url + id, electronicDevice);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    var electronicDeviced = JsonConvert.DeserializeObject<ElectronicDevice>(await client.GetStringAsync(url + id));
                    if (!(electronicDeviced.EId== electronicDevice.EId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["EEdit"] = "Edited Successfully.";
                return RedirectToAction("AdminView","Login");
            }
            ViewBag.EEdit = "Edit Failed.";
            return View(electronicDevice);
        }

        // GET: ElectronicDevices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var electronicDevice = await _context.ElectronicDevice
            //.FirstOrDefaultAsync(m => m.EId == id);
            var electronicDevice = JsonConvert.DeserializeObject<ElectronicDevice>(await client.GetStringAsync(url + id));
            if (electronicDevice == null)
            {
                ViewBag.EDelete = "Product Not Found";
                return NotFound();
            }

            return View(electronicDevice);
        }

        // POST: ElectronicDevices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //var electronicDevice = await _context.ElectronicDevice.FindAsync(id);
            // _context.ElectronicDevice.Remove(electronicDevice);
            // await _context.SaveChangesAsync();
            await client.DeleteAsync(url + id);
            TempData["EDelete"] = "Deleted Successfully";
            return RedirectToAction("AdminView", "Login");
        }

        private bool ElectronicDeviceExists(int id)
        {
            return _context.ElectronicDevice.Any(e => e.EId == id);
        }
    }
}

e-commerce/Views/ElectronicDevices/Create.cshtml
@model e_commerce.Models.ElectronicDevice

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/AdminViewPartial.cshtml";

}
<div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
    <h1>Create</h1>

    <h4>ElectronicDevice</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="EName" class="control-label"></label>
                    <input asp-for="EName" class="form-control" style="width:800px;" />
                    <span asp-validation-for="EName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <select asp-for="Category" asp-items="Html.GetEnumSelectList<Category>()" class="form-control" style="width:800px;"></select>
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" style="width:800px;" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Quantity" class="control-label"></label>
                    <input asp-for="Quantity" class="form-control" style="width:800px;" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rating" class="control-label"></label>
                    <input asp-for="Rating" class="form-control" style="width:800px;" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LaunchDate" class="control-label"></label>
                    <input asp-for="LaunchDate" class="form-control" style="width:800px;" />
                    <span asp-validation-for="LaunchDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" class="form-control" style="width:800px;" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EBrand" class="control-label"></label>
                    <select asp-for="EBrand" asp-items="Html.GetEnumSelectList<EBrand>()" class="form-control" style="width:800px;"></select>
                    <span asp-validation-for="EBrand" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" style="width:800px;" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="FreeDelivery" /> @Html.DisplayNameFor(model => model.FreeDelivery)
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
            @if (ViewBag.ECreate != null)
            {
                <script type="text/javascript">
                        window.onload = function () {
                            alert("@ViewBag.ECreate");
                        };
                </script>
            }
        </div>
    </div>

    <div>
        <a class="btn btn-primary" asp-action="AdminView" asp-controller="Login">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</div>

e-commerce/Views/ElectronicDevices/Delete.cshtml
@model e_commerce.Models.ElectronicDevice

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/AdminViewPartial.cshtml";

}
<div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Electronic Device</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Category)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Quantity)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Rating)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Rating)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LaunchDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LaunchDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ImageFile)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ImageFile)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EBrand)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EBrand)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FreeDelivery)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FreeDelivery)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Active)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Active)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="EId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-primary" asp-action="AdminView" asp-controller="Login">Back to List</a>
        </form>
        @if (ViewBag.EDelete != null)
        {
            <script type="text/javascript">
                        window.onload = function () {
                            alert("@ViewBag.EDelete");
                        };
            </script>
        }
    </div>
</div>

e-commerce/Views/ElectronicDevices/Details.cshtml
@model e_commerce.Models.ElectronicDevice

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/AdminViewPartial.cshtml";

}
<div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
    <h1>Details</h1>

    <div>
        <h4>ElectronicDevice</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ImageFile)
            </dt>
            <dd class="col-sm-10">
                <img src="@Html.DisplayFor(model => model.ImageFile)" style="height:200px; width:200px" class="card-img-top overflow-auto" alt="..." />
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Category)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Quantity)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Rating)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Rating)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LaunchDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LaunchDate)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EBrand)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EBrand)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FreeDelivery)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FreeDelivery)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Active)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Active)
            </dd>
        </dl>
    </div>
    <div>
        <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.EId">Edit</a> |
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.EId">Delete</a> |
        <a class="btn btn-primary" asp-action="AdminView" asp-controller="Login">Back to List</a>
    </div>
</div>

e-commerce/Views/ElectronicDevices/Edit.cshtml
@model e_commerce.Models.ElectronicDevice

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/AdminViewPartial.cshtml";

}
<div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
    <h1>Edit</h1>

    <h4>ElectronicDevice</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="EId" />
                <div class="form-group">
                    <label asp-for="EName" class="control-label"></label>
                    <input asp-for="EName" class="form-control"  style="width:800px;"/>
                    <span asp-validation-for="EName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <select asp-for="Category" asp-items="Html.GetEnumSelectList<Category>()" class="form-control" style="width:800px;"></select>
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" style="width:800px;"/>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Quantity" class="control-label"></label>
                    <input asp-for="Quantity" class="form-control"  style="width:800px;"/>
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rating" class="control-label"></label>
                    <input asp-for="Rating" class="form-control" style="width:800px;" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LaunchDate" class="control-label"></label>
                    <input asp-for="LaunchDate" class="form-control" style="width:800px;" />
                    <span asp-validation-for="LaunchDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" class="form-control" style="width:800px;" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EBrand" class="control-label"></label>
                    <select asp-for="EBrand" asp-items="Html.GetEnumSelectList<EBrand>()" class="form-control" style="width:800px;"></select>
                    <span asp-validation-for="EBrand" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" style="width:800px;" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="FreeDelivery"  style="width:800px;"/> @Html.DisplayNameFor(model => model.FreeDelivery)
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Active" style="width:800px;" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            @if (ViewBag.EEdit != null)
            {
                <script type="text/javascript">
                        window.onload = function () {
                            alert("@ViewBag.EEdit");
                        };
                </script>
            }
        </div>
    </div>

    <div>
        <a class="btn btn-primary"  asp-action="AdminView" asp-controller="Login">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</div>

e-commerce/Views/ElectronicDevices/ElectronicPartial.cshtml
@model IEnumerable<e_commerce.Models.ElectronicDevice>

<p>
    <a asp-controller="ElectronicDevices" asp-action="Create">Create New</a>
</p>
<div class="row overflow-auto">
    @foreach (var item in Model)
    {

        <div class="col-md-3 overflow-auto">



            <div class="card">


                <a asp-controller="ElectronicDevices" asp-action="Details" asp-route-id="@item.EId"> <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." /></a>

                <div class="card-body">

                    <h5 class="card-title">

                        <b>@item.EName</b>

                        <span class="bg-success" style="color:white">

                            @item.Rating

                            <span class="glyphicon glyphicon-star"></span>

                        </span>

                    </h5>

                    <h5 class="card-title">Rs @item.Price <s>Rs. 250 </s> 20% <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>

                    <br>

                    <p class="card-text">@item.Description</p>



                </div>





            </div>
            <br />

        </div>

    }
</div>

e-commerce/Views/ElectronicDevices/Index.cshtml
@model IEnumerable<e_commerce.Models.ElectronicDevice>

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Third Handson</title>



    <!-- Bootstrap -->

    <link href="Bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js></script>

    <script src=https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">





    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

      <script src=https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js></script>

      <script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script>

    <![endif]-->

    <style>

        .i-plain:hover {
            color: red
        }
    </style>
    

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">

        <a class="navbar-brand navbar-left" href="#">hTrack</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#colNav">

            <span class="navbar-toggler-icon"></span>

        </button>

        <div class="collapse navbar-collapse justify-content-sm-end" id="colNav">

            <ul class="navbar-nav navbar-right">

                <li class="nav-item">

                    <a class="nav-link" href="#">Products</a>

                </li>

                <li class="nav-item">

                    <a class="nav-link" href="#">Goals</a>

                </li>

            </ul>

        </div>

    </nav>

    <br>



    <div class="container-fluid padding">

        <h2>Products</h2>

        <br />
        <p>
            <a asp-controller="ElectronicDevices" asp-action="Create">Create New</a>
        </p>
        <div class="row overflow-auto">
            @foreach (var item in Model)
            {

                <div class="col-md-3 overflow-auto">



                    <div class="card h-100" style="background-image: url('https://media.istockphoto.com/vectors/crepe-paper-textured-grunge-vector-tricolour-faded-background-with-vector-id1264073605?k=6&m=1264073605&s=612x612&w=0&h=P31yF3S7XWPIvIINd5uTfuwl1MUa0nqzTRRaG0mFay4='); backdrop-filter: blur(50px); background-size:cover; background-repeat: no-repeat;">


                        <a asp-controller="ElectronicDevices" asp-action="Details" asp-route-id="@item.EId"> <img src="@item.ImageFile" style="height:200px" class="card-img-top overflow-auto" alt="..." /></a>

                        <div class="card-body">

                            <h5 class="card-title">

                                <b>@item.EName</b>

                                <span class="bg-success" style="color:white">

                                    @item.Rating

                                    <span class="glyphicon glyphicon-star"></span>

                                </span>

                            </h5>

                            <h5 class="card-title">Rs @item.Price <s>Rs. 250 </s> 20% <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span></h5>

                            <br>

                            <p class="card-text">@item.Description</p>

                            

                        </div>





                    </div>
                    <br />

                </div>

            }
        </div>

    </div>





    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src=https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js></script>



    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="Bootstrap/js/bootstrap.min.js"></script>

</body>

</html>