e-commerce/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class AddressesController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
        private readonly string AddressURL = ApiURLS.GetAddressUrl();
        private readonly string CustomerURL = ApiURLS.GetCustomerUrl();
       
        public AddressesController(ShoppingDbContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username1") != null)
            {
                var shoppingDbContext = JsonConvert.DeserializeObject<List<Address>>(await client.GetStringAsync(AddressURL)).ToList().Where(a => a.CustId.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));
                //var shoppingDbContext = _context.Address.Include(c => c.Customer).Where(a => a.CustId.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));
                var count = shoppingDbContext.ToList().Count();
                if (shoppingDbContext != null && count > 0)
                {
                    return View(shoppingDbContext.ToList());
                }
                else
                {
                    return RedirectToAction("Create");
                }

            }
            else
            {
                return RedirectToAction("Customer", "Login");
            }
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var address = await _context.Address
            //  .Include(a => a.Customer)
            //.FirstOrDefaultAsync(m => m.AddressId == id);
            var address = JsonConvert.DeserializeObject<Address>(await client.GetStringAsync(AddressURL + id));
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public async Task<IActionResult> Create()
        {
            var customerList = JsonConvert.DeserializeObject<List<Customer>>(await client.GetStringAsync(CustomerURL)).ToList();
            ViewBag.CustId = new SelectList(customerList, "UserId", "Email");
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AddressId,FirstName,LastName,EmailAddress,PhoneNo,AddressLineone,AddressLinetwo,Country,City,State,PinCode,CustId")] Address address)
        {
            if (ModelState.IsValid)
            {
                // _context.Add(address);
                // await _context.SaveChangesAsync();
                await client.PostAsJsonAsync<Address>(AddressURL, address);
                return RedirectToAction(nameof(Index));
            }
           // var customerOBJ = _context.Address;
            var customerList = JsonConvert.DeserializeObject<DbSet<Customer>>(await client.GetStringAsync(CustomerURL));
            ViewData["CustId"] = new SelectList(customerList, "UserId", "Email", address.CustId);
            return View(address);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var address = await _context.Address.FindAsync(id);
            var address = JsonConvert.DeserializeObject<Address>(await client.GetStringAsync(AddressURL + id));
            if (address == null)
            {
                return NotFound();
            }
            var customerList = JsonConvert.DeserializeObject<List<Customer>>(await client.GetStringAsync(CustomerURL)).ToList();
            ViewData["CustId"] = new SelectList(customerList, "UserId", "Email", address.CustId);
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AddressId,FirstName,LastName,EmailAddress,PhoneNo,AddressLineone,AddressLinetwo,Country,City,State,PinCode,CustId")] Address address)
        {
            if (id != address.AddressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // _context.Update(address);
                    // await _context.SaveChangesAsync();
                    await client.PutAsJsonAsync<Address>(AddressURL + id, address);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var addresss = JsonConvert.DeserializeObject<Address>(await client.GetStringAsync(AddressURL + id));
                    if (!(addresss.AddressId== address.AddressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var customerList = JsonConvert.DeserializeObject<List<Customer>>(await client.GetStringAsync(CustomerURL)).ToList();
            ViewData["CustId"] = new SelectList(customerList, "UserId", "Email", address.CustId);
            return View(address);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //  var address = await _context.Address
            //   .Include(a => a.Customer)
            //   .FirstOrDefaultAsync(m => m.AddressId == id);
            var address = JsonConvert.DeserializeObject<Address>(await client.GetStringAsync(AddressURL + id));
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // var address = await _context.Address.FindAsync(id);
            ////_context.Address.Remove(address);
            // await _context.SaveChangesAsync();
            await client.DeleteAsync(AddressURL + id);
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.AddressId == id);
        }
    }
}

e-commerce/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Context;
using e_commerce.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using e_commerce.ViewModel;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;

namespace e_commerce.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ShoppingDbContext _context;
        HttpClient client = new HttpClient();
       
        private readonly string CustomerURL = ApiURLS.GetCustomerUrl();
        private readonly string ElectronicURL = ApiURLS.GetElectronicDevicesUrl();
        private readonly string  FashionURL = ApiURLS.GetFashionUrl();
        private readonly string HomeDecorURL = ApiURLS.GetHomeDecorUrl();
        private readonly string OrderReviewURL = ApiURLS.GetOrderReviewUrl();
        private readonly string PaymentURL = ApiURLS.GetPaymentUrl();
        private readonly string AddressURL = ApiURLS.GetAddressUrl();
        private readonly string CartURL =ApiURLS.GetCartUrl();
        private readonly string OrderURL = ApiURLS.GetOrderUrl();



        public OrdersController(ShoppingDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username1") != null)
            {
                try
                {
                    var AddressList = JsonConvert.DeserializeObject<List<Address>>(await client.GetStringAsync(AddressURL)).ToList();
                    var addressobj = AddressList.FirstOrDefault(a => a.CustId.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));

                    var OrderList = JsonConvert.DeserializeObject<List<Order>>(await client.GetStringAsync(OrderURL));
                    var shoppingDbContext = OrderList.Where(a => a.AddrId.Equals(addressobj.AddressId)).ToList();

                    var count = shoppingDbContext.Count();
                    if (shoppingDbContext != null && count > 0)
                    {
                        return View(shoppingDbContext.ToList());
                    }
                }
                catch
                {
                    return RedirectToAction("OrderEmpty");
                }


            }

            else
            {
                return RedirectToAction("Customer", "Login");
            }
            return RedirectToAction("OrderEmpty");
           
           
        }
        [HttpPost]
        public async Task<IActionResult> GetDate(DateTime SD, DateTime ED)
        {
            var AddressList = JsonConvert.DeserializeObject<List<Address>>(await client.GetStringAsync(AddressURL)).ToList();
            var addressobj = AddressList.FirstOrDefault(a => a.CustId.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));

            var OrderList = JsonConvert.DeserializeObject<List<Order>>(await client.GetStringAsync(OrderURL)).ToList();
            var shoppingDbContext = OrderList.Where(a => a.AddrId.Equals(addressobj.AddressId)).Where(a=>a.DateOfOrder >= SD && a.DateOfOrder <= ED);
            return View("Index", shoppingDbContext.ToList());
        }

       /* [HttpPost] 
        public ActionResult GetDate(DateTime date1, DateTime date2)
        {
           // HttpContext.Session.SetString("fromDate", date1.ToString());
           // HttpContext.Session.SetString("endDate", date2.ToString());
            return RedirectToAction("Index");
        }*/

        
        public ActionResult OrderEmpty()
        {
            return View();

        }
        public async Task<IActionResult> PaymentProcess()
        {
            var CartList = JsonConvert.DeserializeObject<List<Cart>>(await client.GetStringAsync(CartURL)).ToList();
            var cartobj = CartList.Where(a => a.Userid.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));
            ViewBag.Amount = cartobj.ToList().Sum(a => a.Price * a.Quantity);
            ViewBag.CartList = cartobj;
            return View();
        }
        [HttpPost]
       
        public async Task<IActionResult> PaymentProcess([Bind("CardNumber,Password")] Payment payment)
        {
            var PaymentList = JsonConvert.DeserializeObject<List<Payment>>(await client.GetStringAsync(PaymentURL)).ToList();
            var paymentobj = PaymentList.FirstOrDefault(a => a.CardHolderName.ToLower().Equals(HttpContext.Session.GetString("username1").ToLower()));

            var CartList = JsonConvert.DeserializeObject<List<Cart>>(await client.GetStringAsync(CartURL)).ToList();
            var cartobj = CartList.Where(a => a.Userid.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId"))));
            ViewBag.CartList = cartobj;
            ViewBag.Amount1 = cartobj.ToList().Sum(a => a.Price * a.Quantity);
            ViewBag.Amount2 = cartobj.ToList().Sum(a => (Convert.ToInt32(a.Price * a.Quantity)-(Convert.ToInt32(a.Price * a.Quantity*0.02))));

           
                if (paymentobj.CardNumber == payment.CardNumber && paymentobj.Password == payment.Password)
                {
                    if (paymentobj.Balance >= ViewBag.Amount1)
                    {

                        foreach (var item in cartobj)
                        {
                            if (item.Category == "Laptop" || item.Category == "Mobile" || item.Category == "EarPhone" || item.Category == "Camera" || item.Category == "Television" || item.Category == "Printers")
                            {
                                 var ElectronicDeviceList = JsonConvert.DeserializeObject<List<ElectronicDevice>>(await client.GetStringAsync(ElectronicURL)).ToList();
                            var productobj = ElectronicDeviceList.FirstOrDefault(a => a.EName.Equals(item.productName));
                                productobj.Quantity = productobj.Quantity - item.Quantity;
                            // _context.ElectronicDevice.Update(productobj);
                            await client.PutAsJsonAsync<ElectronicDevice>(ElectronicURL + productobj.EId, productobj);

                        }
                            else if (item.Category == "Watch" || item.Category == "Wallet" || item.Category == "Sunglasses")
                            {
                                var FashionList = JsonConvert.DeserializeObject<List<Fashion>>(await client.GetStringAsync(FashionURL)).ToList();
                                var productobj1 = FashionList.FirstOrDefault(a => a.FName.Equals(item.productName));
                                productobj1.Quantity = productobj1.Quantity - item.Quantity;
                            // _context.Fashion.Update(productobj1);
                            await client.PutAsJsonAsync<Fashion>(FashionURL + productobj1.FId, productobj1);

                        }
                            else if (item.Category == "Furniture" || item.Category == "SecurityCameras" || item.Category == "SmartHomelightening" || item.Category == "Clocks" || item.Category == "Mirrors" || item.Category == "Wallpapers" || item.Category == "DreamCatcher")
                            {
                            var HomeDecorsList = JsonConvert.DeserializeObject<List<HomeDecor>>(await client.GetStringAsync(HomeDecorURL)).ToList();
                            var productobj2 = HomeDecorsList.FirstOrDefault(a => a.HName.Equals(item.productName));
                                productobj2.Quantity = productobj2.Quantity - item.Quantity;
                            // _context.HomeDecor.Update(productobj2);
                            await client.PutAsJsonAsync<HomeDecor>(HomeDecorURL + productobj2.HId, productobj2);

                        }

                        }
                        paymentobj.Balance = paymentobj.Balance - ViewBag.Amount2;
                    // _context.Payment.Update(paymentobj);
                        await client.PutAsJsonAsync<Payment>(PaymentURL + paymentobj.PId, paymentobj);
                        var AddressList = JsonConvert.DeserializeObject<List<Address>>(await client.GetStringAsync(AddressURL));
                        
                        var orderobj = new Order();
                        orderobj.Price = ViewBag.Amount1;
                        orderobj.AddrId = AddressList.FirstOrDefault(a=>a.AddressId.Equals(Convert.ToInt32(HttpContext.Session.GetString("custId")))).AddressId;
                        orderobj.DateOfOrder = DateTime.Now;
                        orderobj.PaymentMode = paymentmode.creditCard;
                        orderobj.OrderStatus = OrderStatus.Progress;
                        orderobj.DateOfDelivery = DateTime.Now.AddDays(1);
                    // _context.Order.Add(orderobj);
                    //_context.SaveChanges();
                    await client.PostAsJsonAsync<Order>(OrderURL, orderobj);
                    TempData["PSucess"] = "Payment Was Successfull and Order is Placed";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.InsufficientAmount = "Insufficient amount";
                        ModelState.AddModelError("", "Insufficient amount");
                    }


                }
                else
                {
                    ViewBag.InvalidCredentials = "Invalid Credentials";
                    ModelState.AddModelError("", "Invalid Credentials");

                }
           
           
            return View(payment);
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var order = await _context.Order

e-commerce/Views/Payments/Create.cshtml
@model e_commerce.Models.Payment

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}
<div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
    <h2>Create</h2>

    <h4>Payment</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CardNumber" class="control-label"></label>
                    <input asp-for="CardNumber" class="form-control" style="width:800px" />
                    <span asp-validation-for="CardNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" style="width:800px"/>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CardHolderName" class="control-label"></label>
                    <input asp-for="CardHolderName" class="form-control" style="width:800px"/>
                    <span asp-validation-for="CardHolderName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Balance" class="control-label"></label>
                    <input asp-for="Balance" class="form-control" style="width:800px"/>
                    <span asp-validation-for="Balance" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a class="btn btn-primary" asp-action="Index">Back to Payment Information</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</div>

e-commerce/Views/Payments/Delete.cshtml
@model e_commerce.Models.Payment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}
<div class="container" style="background-color:lavender">
    <div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Payment</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CardNumber)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CardNumber)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Password)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Password)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CardHolderName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CardHolderName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Balance)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Balance)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="PId" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a class="btn btn-primary" asp-action="Index">Back to Payment Information</a>
            </form>
        </div>
    </div>
    </div>

e-commerce/Views/Payments/Details.cshtml
@model e_commerce.Models.Payment

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CardHolderName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CardHolderName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

e-commerce/Views/Payments/Edit.cshtml
@model e_commerce.Models.Payment

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}
<div class="container" style="background-color:lavender">
    <div class="jumbotron" style="display:inline-block; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
        <h2>Edit</h2>

        <h4>Payment</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="PId" />
                    <div class="form-group">
                        <label asp-for="CardNumber" class="control-label"></label>
                        <input asp-for="CardNumber" class="form-control" style="width:800px" />
                        <span asp-validation-for="CardNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" style="width:800px" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CardHolderName" class="control-label"></label>
                        <input asp-for="CardHolderName" class="form-control" style="width:800px" />
                        <span asp-validation-for="CardHolderName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Balance" class="control-label"></label>
                        <input asp-for="Balance" class="form-control" style="width:800px" />
                        <span asp-validation-for="Balance" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a class="btn btn-primary" asp-action="Index">Back to Payment Information</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
    </div>
</div>

e-commerce/Views/Payments/Index.cshtml
@model IEnumerable<e_commerce.Models.Payment>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/CustomerViewPartial.cshtml";
}

    <div class="jumbotron container-fluid" style="display:inline-block; background-color:lavender; align-content:center; margin:auto; margin-block-start:1%; margin-inline-start:1%">
        <a class="btn btn-primary" asp-action="Index" asp-controller="Addresses">Back To Address</a>
        <br />
        <h2>Payment</h2>


        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CardNumber)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.CardHolderName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Balance)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CardNumber)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.CardHolderName)
                        </td>
                        <td>
                           RS. @Html.DisplayFor(modelItem => item.Balance)
                        </td>
                        <td>
                            <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.PId">Edit</a> |

                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.PId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-primary" asp-action="PaymentProcess" asp-controller="Orders">
            Proceed To Payment <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
            </svg>
        </a>
    </div>